<?php 
/**
    Generated by PHPistols 
    The PHP code generator https://www.phpistols.com
*/

class ViewUsers {


function menu(){
	?>
	<p><a class="btn" href="controller.php?">View list</a>
	<a class="btn" href="controller.php?&task=edit-list">Edit list</a>
	<a class="btn btn-primary" href="controller.php?&task=edit">Add Users</a>
	<?php
}

function header(){
    echo '<!DOCTYPE html>
    <html>
        <head>
        <title>users</title>
        <!-- Bootstrap -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="container">
            <h1>users</h1>
    ';
}

function footer(){
    echo '</div>
    </body>
</html>';
}


function pagination($numberOfPages, $curentPage, $link){
	//if($numberOfPages >1){
		echo '<nav aria-label="Page navigation"><ul class="pagination">';
		for($i=1; $i<=$numberOfPages; $i++){
			if($i == $curentPage){
				?>
				<li class="active"><a href="<?=$link?>page=<?=$i?>"><?=$i?></a></li>
				<?php
			}
			else{
				?>
				<li><a href="<?=$link?>page=<?=$i?>"><?=$i?></a></li>
				<?php
			}
		}
		echo '</ul></nav>';
	//}
}

function message($message, $messageType='success'){
    if($message != ''){
    ?>
    <div class="alert alert-<?=$messageType?>">
        <?=$message?>
    </div>
    <?php
    }
}

function form($data, $message=null){
    $this->message($message['text'], $message['type']);
	?>
	<div>
	    <h2>Edit / Add</h2>
		<form method="POST" action="<?=$_SERVER['REQUEST_URI']?>">
		<fieldset>

	

        <div class="form-group">
		<label class="control-label">Name:</label>
		<input class="form-control" type="text" name="name" id="name" size="10" value="<?=htmlentities($data->name)?>"/>
	    </div>
	

        <div class="form-group">
		<label class="control-label">Email:</label>
		<input class="form-control" type="text" name="email" id="email" size="10" value="<?=htmlentities($data->email)?>"/>
	    </div>
	
		<div class="form-group">
		<input type="hidden" name="userId" id="id" value="<?=$data->userId ?>"/>
		<input type="submit" name="Envoyer" title="Envoyer" value="Save" class="btn btn-primary">
		</div>



	</fieldset>
	</form>
	</div>
	<?php
	}
	

function displayList($data, $link='', $orderBy='', $order='desc', $message=null){
    $this->message($message['text'], $message['type']);


	?>
    <h2>List</h2>
	<table class="table table-bordered">
	<thead>
	<tr>	<th scope="col" id="userId"><a href="<?=$link?>&orderBy=userId&order=<?php if($orderBy == "userId") echo $order; else echo 'asc';?>">UserId</a></th>
	<th scope="col" id="name"><a href="<?=$link?>&orderBy=name&order=<?php if($orderBy == "name") echo $order; else echo 'asc';?>">Name</a></th>
	<th scope="col" id="email"><a href="<?=$link?>&orderBy=email&order=<?php if($orderBy == "email") echo $order; else echo 'asc';?>">Email</a></th>

		<th></th>
	</tr>
	</thead>
	<tbody>
	<?php
	$i=1;


	foreach ($data as $element){
		?>
		<tr>
		<td><?php echo $element['userId']?></td>
		<td><?php echo $element['name']?></td>
		<td><?php echo $element['email']?></td>
	
			<td><a href="controller.php?&task=view&userId=<?php echo $element['userId']?>" class="btn">View</a></td>
		</tr>
		<?php
	}?>
	</tbody>
	</table>
	<?php



		?>
	<tfoot>
	<tr>
	<td colspan="6" class="phppistolsTFooter"></td>
	</tr>
	</tfoot>

	</table>
	<?php
}


	function displayDetails($data, $message=null){
        $this->message($message['text'], $message['type']);
	

	$i=1;

	if ($data->userId != null){
	?>
	<h2>View</h2>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
		        <h6>userId: <?php echo $data->userId?></h6>
		        <h6>name: <?php echo $data->name?></h6>
		        <h6>email: <?php echo $data->email?></h6>
	        </div>
	    </div>
	</div>
	<?php
    }
    else{
        $this->message('No data', 'warning');
    }



}


function editList($data, $link='', $orderBy='', $order='desc', $message=null){
    $this->message($message['text'], $message['type']);


	?>
    <h2>Edit List</h2>
	<table class="table table-bordered">
	<thead>
	<tr>	<th scope="col" id="userId"><a href="<?=$link?>&orderBy=userId&order=<?php if($orderBy == "userId") echo $order; else echo 'asc';?>">UserId</a></th>
	<th scope="col" id="name"><a href="<?=$link?>&orderBy=name&order=<?php if($orderBy == "name") echo $order; else echo 'asc';?>">Name</a></th>
	<th scope="col" id="email"><a href="<?=$link?>&orderBy=email&order=<?php if($orderBy == "email") echo $order; else echo 'asc';?>">Email</a></th>

		<th></th>
		<th></th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	<?php
	$i=1;


	foreach ($data as $element){
		?>
		<tr>
		<td><?php echo $element['userId']?></td>
		<td><?php echo $element['name']?></td>
		<td><?php echo $element['email']?></td>
	
			<td><a href="controller.php?&task=view&userId=<?php echo $element['userId']?>" class="btn">View</a></td>
			<td><a href="controller.php?&task=edit&userId=<?php echo $element['userId']?>" class="btn btn-primary">Edit</a></td>
			<td><a href="controller.php?&task=del&userId=<?php echo $element['userId']?>" class="btn btn-danger">Del</a></td>
		</tr>
		<?php
	}?>
	</tbody>
	</table>
	<?php



		?>
	<tfoot>
	<tr>
	<td colspan="6" class="phppistolsTFooter"></td>
	</tr>
	</tfoot>

	</table>
	<?php
}

}
	